site_name: zhelper 帮助文档
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - toc.integrate
  palette:
    primary: red

extra_javascript:
  - javascript/extra.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 一些TIPS: tips/index.md
  - 电子书搜索网站: search/index.md
  - 电子书工具网站: tool/index.md